apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: eh1vawaad-nodejs 
  janus-idp.io/tekton: eh1vawaad-nodejs
  backstage.io/kubernetes-id: eh1vawaad-nodejs
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: eh1vawaad-nodejs
resources:
  - ci-tekton.yaml
  - application-dev.yaml
  - application-stage.yaml
  - application-prod.yaml