apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    tad.gitops.set/image: ".spec.template.spec.containers[0].image"
    tad.gitops.get/image: ".spec.template.spec.containers[0].image"
    tad.gitops.set/replicas: ".spec.replicas"
    tad.gitops.get/replicas: ".spec.replicas"
  name: eh1vawaad-nodejs
spec:
  replicas: 1
  template:
    spec:
      containers:
        - image: quay.io/rhtap_qe/rhtap-qe-nodejs:fa7272ca0147e755e68ad7fd3b1eb9df9a874a68@sha256:dd19c9568650fd10ec4b659c2f33cd3840c45577897fe7b08fd327a0dd5269a2
          name: container-image
